export const Routess = {
  About: "/about",
  // Base: "/",
  Home: "/app//*",
  SignOut: "/app/signout",
  HelpAndSupport: "/support",
  Auth: "/auth",
  Login: "/",
  LoginPassword: "/auth/login/password",
  Signup: "/signup",
  OauthSignup: "/auth/oauth-signup",
  OauthConfirm: "/auth/oauth-confirm",
  OauthLand: "/auth/oauth",
  VerifyOTP: "/auth/signup/verify-otp",
  ForgotPassword: "/auth/password-forgotten",
  VerifyPasswordOTP: "/auth/password-forgotten/verify-otp",
  TermsAndCondition: "/legal/terms-and-conditions",
  PrivacyPolicies: "/legal/privacy-policies",
  StoreSection: "/app/productpage",
  InfluencerApplication: "/app/influencerapplicaton",
  SuperAdmin: "/app/superadmin",
  userAlreadyexist:"/userExist",


  // **********************//
  // Dashboard:"/app/home",
  DataPrepare:"/app/dataprepare",
  TextAnalysis:"/app/textanalysis/summary",
  Summary:"/app/textanalysis/summary",
  Translate:"/app/textanalysis/translate",
  TextInsight:"/app/textanalysis/textinsight",
  ContentModeration:"/app/textanalysis/Moderation",
  QndA:"/app/textanalysis/QndA",
  Monitoring:"/app/textanalysis/monitoring",
  Search:"/app/textanalysis/search",
  Chat:"/app/textanalysis/chat-bot",
  SpeechAnalytics:"/app/speechanalytics/realtime",
  RealTime:"/app/speechanalytics/realtime",
  Recorded:"/app/speechanalytics/recorded",
  PostCall:"/app/speechanalytics/postcall",
  CallSummary:"/app/speechanalytics/callsummary",
  CallManagement:"/app/speechanalytics/callManagement",
  CallLogs:"/app/speechanalytics/call-logs",
  LogServer:"/app/speechanalytics/logserver"


};
